Add option to calculate explicit efficiencies at different wavelengths.
Add efficiency wavelength derivative plotter to show_spectrum().
Currently not working due to issues assigning torch.DoubleTensor to np array,
but should be easy fix

I think I have fixed the RuntimeError: internal asset failed and/or
RuntimeError: bad_optional_access by setting and restoring self.angle AND self.wavelength
in the "PD*" functions. Still don't know the deeper cause.
Could be due to the efficiency functions setting self.angle and self.wavelength internally.